name: Build Stencil

on:
  workflow_call:
  # Make this a reusable workflow, no value needed
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows

permissions:
  contents: read

jobs:
  build_core:
    name: Core
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸ•¸ï¸ Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ğŸ—ï¸ Core Build
        run: npm run build -- --ci
        shell: bash

      - name: ğŸ”¬ Validate Build
        run: npm run test.dist
        shell: bash

      - name: ğŸ”¬ Validate Testing
        run: npm run test.testing
        shell: bash

      - name: ğŸ“¤ Upload Build Artifacts
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: ./.github/workflows/actions/upload-archive
        with:
          name: stencil-core
          output: stencil-core-build.zip
          paths: cli compiler dev-server internal mock-doc scripts/build screenshot sys testing
