name: CI

on:
  pull_request:
  push:

jobs:
  test-core:
    name: Core Jest
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸŸ¢ Use Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
          cache: 'npm'
      - name: ğŸ•¸ï¸ Install
        run: npm ci
      - name: ğŸ—ï¸ Build (generate testing artifacts)
        run: npm run build -- --ci
      - name: ğŸ§ª Run Jest (core)
        run: npm run test.jest

  test-bundler:
    name: Bundler Jest
    runs-on: ubuntu-latest
    needs: test-core
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
          cache: 'npm'
      - name: ğŸ•¸ï¸ Install
        run: npm ci
      - name: ğŸ—ï¸ Build core (required by bundler job)
        run: npm run build -- --ci
      - name: ğŸ—ï¸ Build bundler artifacts
        run: npm run --prefix test/bundler build
      - name: ğŸ§ª Run Bundler tests
        run: npm run test.bundler
