name: Lint and Format Stencil (Check)

on:
  merge_group:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

permissions:
  contents: read

jobs:
  format:
    name: Check
    runs-on: 'ubuntu-22.04'
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸ•¸ï¸ Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ğŸ–Œï¸ ESLint
        run: npm run lint

      - name: ğŸ–Œï¸ Prettier Check
        run: npm run prettier.dry-run
        shell: bash

      - name: ğŸ“š Spellcheck
        run: npm run spellcheck
