name: 'Stencil Nightly Release'

on:
  workflow_call:

permissions:
  contents: write
  id-token: write

jobs:
  build_core:
    name: ðŸ—ï¸ Build
    uses: ./.github/workflows/build.yml

  get-nightly-version:
    name: ðŸ” Get Nightly Build Version
    needs: [build_core]
    runs-on: ubuntu-22.04
    outputs:
      nightly-version: ${{ steps.get-nightly-version.outputs.NIGHTLY_VERSION }}
    steps:
      - name: ðŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ðŸ•¸ï¸ Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ðŸ“¥ Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: stencil-core
          path: .
          filename: stencil-core-build.zip

      - name: ðŸ”Ž Get Version
        id: get-nightly-version
        run: |
          # A unique string to publish Stencil under
          # e.g. "3.0.1-dev.1677185104.7c87e34"
          #
          # Note: A 'nightly' build is just a 'dev' build that is published at
          # night, under the 'nightly' tag in npm
          #
          # Pull this value from the compiled artifacts
          NIGHTLY_VERSION=$(./bin/stencil version)

          echo "Using version $NIGHTLY_VERSION"

          # store a key/value pair in GITHUB_OUTPUT
          # e.g. "NIGHTLY_VERSION=3.0.1-dev.1677185104.7c87e34"
          echo "NIGHTLY_VERSION=$NIGHTLY_VERSION" >> $GITHUB_OUTPUT

        shell: bash

  release-stencil-nightly-build:
    name: ðŸš€ Publish Nightly Build
    needs: [get-nightly-version, build_core]
    uses: ./.github/workflows/publish-npm.yml
    with:
      tag: nightly
      version: ${{ needs.get-nightly-version.outputs.nightly-version }}
