name: Bundler Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

permissions:
  contents: read

jobs:
  bundler_tests:
    name: Verify Bundlers
    runs-on: 'ubuntu-22.04'
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸ•¸ï¸ Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ğŸ“¥ Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: stencil-core
          path: .
          filename: stencil-core-build.zip

      - name: ğŸ§¼ Sanitize npm config for public registry
        shell: bash
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set always-auth false
          npm config delete '//registry.npmjs.org/:_authToken' || true
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
        env:
          NPM_TOKEN: ""

      - name: ğŸ§ª Bundler Tests
        run: npm run test.bundlers
        shell: bash

      - name: ğŸ” Check Git Context
        uses: ./.github/workflows/actions/check-git-context
