name: WebdriverIO Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

permissions:
  contents: read

jobs:
  wdio_test:
    name: Run WebdriverIO Component Tests (${{ matrix.browser }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # browser: [CHROME, FIREFOX, EDGE]
        browser: [CHROME]

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸ•¸ï¸ Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ğŸŸ¢ Use Node Version from Volta
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          # pull the version to use from the volta key in package.json
          node-version-file: './test/wdio/package.json'
          cache: 'npm'

      - name: ğŸ“¥ Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: stencil-core
          path: .
          filename: stencil-core-build.zip

      - name: ğŸ§ª Run WebdriverIO Component Tests
        run: npm run test.wdio
        shell: bash
        env:
          BROWSER: ${{ matrix.browser }}

      - name: ğŸ“¦ Check Git Context
        uses: ./.github/workflows/actions/check-git-context
